---
title: "How Good Are Confidence Intervals?"
subtitle: "Determining Default CI Width Selection From Simulations"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
editor_options:
  chunk_output_type: console
---
```{r setup, message=FALSE, warning=FALSE, include=FALSE}
require(tidyverse)
require(tidymodels)
require(nationalparkcolors)
require(RColorBrewer)
```

### Analysis date: `r format(Sys.time(), '%B %d, %Y')`

```{r message=FALSE, warning=FALSE, include=FALSE}
setwd("~/Documents/projects/NemaScan_Performance/")
load(file = "data/NemaScan_Performance.CeNDR2020_PowerPrecision_GAMMA.20200909.RData")
dat <- simuation.metrics.df %>%
  tidyr::separate(col = sim,
                  into = c("nQTL","Rep","h2","MAF","effect_range","strain_set"), 
                  sep = "_", remove = F) %>%
  tidyr::separate(col = QTL,
                  into = c("CHROM","POS"), 
                  sep = ":", remove = F) %>%
  dplyr::mutate(h2 = as.factor(h2),
                POS = as.numeric(POS))
```

### NemaScan simulation performance was assessed with the following experimental parameters:
* ###### Number of Simulated QTL: ```r levels(as.factor(dat$nQTL))```
* ###### Sample Population(s): ```r levels(as.factor(dat$strain_set))```
* ###### Heritability(ies): ```r levels(as.factor(dat$h2))```
* ###### MAF(s): ```r levels(as.factor(dat$MAF))```
* ###### Number of Replicates per Regime: ```r max(as.numeric(dat$Rep))```
* ###### QTL Effect Range: ```r levels(as.factor(dat$effect_range))```

```{r simulated QTL locations, echo=FALSE}
dat %>%
  dplyr::filter(Simulated == TRUE) %>%
  dplyr::filter(!is.na(CHROM)) %>%
  ggplot(mapping = aes(x = POS/1000000, y = Effect)) + 
  theme_bw() + 
  geom_point() + 
  facet_grid(.~CHROM, drop = TRUE) + 
  labs(x = "Genomic position (Mb)",
       y = "Causal QTL Effect",
       title = "Where were QTL Simulated?")

dat %>%
  dplyr::filter(Simulated == TRUE) %>%
  dplyr::filter(algorithm == "LMM-EXACT") %>%
  dplyr::filter(!is.na(CHROM)) %>%
  ggplot(mapping = aes(x = Frequency, fill = Simulated)) +
  theme_minimal() + 
  geom_density() + 
  scale_fill_manual(values = nationalparkcolors::park_palettes$RockyMountains[1]) + 
  theme(legend.position = "none") + 
  xlim(c(0.05,0.5)) + 
  labs(x = "Minor Allele Frequency",
       y = "Frequency of Simulated QTL (Smoothed Density)")
```

```{r power precision resolution, echo=FALSE}
power <- dat %>%
  dplyr::group_by(h2, algorithm) %>%
  yardstick::sens(truth = Simulated, estimate = Detected) %>%
  dplyr::mutate(.metric = "Power")

precision <- dat %>%
  dplyr::group_by(h2, algorithm) %>%
  yardstick::precision(truth = Simulated, estimate = Detected) %>%
  dplyr::mutate(.metric = "Precision")

resolution <- dat %>%
  dplyr::filter(Detected == TRUE) %>%
  dplyr::filter(!is.na(var.exp)) %>%
  dplyr::select(CHROM, POS, Simulated, Frequency, interval_size, algorithm, h2, var.exp) %>%
  dplyr::group_by(h2, algorithm) %>%
  dplyr::summarise(mean(interval_size), median(interval_size), sd(interval_size), 
                   mean(var.exp), median(var.exp), sd(var.exp))

summarized <- power %>%
  dplyr::full_join(., precision) %>%
  tidyr::pivot_wider(names_from = .metric, values_from = .estimate) %>%
  dplyr::left_join(.,resolution) %>%
  dplyr::mutate(mean.interval.Mb = `mean(interval_size)`/1000000,
                median.interval.Mb = `median(interval_size)`/1000000,
                sd.interval.Mb = `sd(interval_size)`/1000000, 
                mean.PVE = `mean(var.exp)`*100,
                median.PVE = `median(var.exp)`*100,
                sd.PVE = `sd(var.exp)`*100, 
                .keep = "unused")
```

```{r closest FP calculation, echo=FALSE, message=FALSE, warning=FALSE}
reps <- dat %>%
  dplyr::group_by(h2, Rep, algorithm) %>%
  tidyr::nest()

# data = reps$data[[214]]
# rep = reps$Rep[[214]]
# h2 = reps$h2[[214]]
# algorithm = reps$algorithm[[214]]

closest.FP.calc <- function(data, rep, h2, algorithm){
# ALL REPS SEPARATED:
  chrom.split <- data %>%
    dplyr::group_by(CHROM) %>%
    tidyr::nest()
# CHROMOSOME LOOP START
  closest.FP <- list()
  for(i in 1:length(chrom.split$data)){
  rep.CHROM <- chrom.split$data[[i]]
# SEARCH FOR CLOSEST SIMULATED QTL
# CALCULATE ABS(DISTANCE) FROM IT
  if(TRUE %in% rep.CHROM$Simulated){
    n.true.qtl <- length(rep.CHROM$Simulated[which(rep.CHROM$Simulated == TRUE)])
    # more than 1 simulated QTL on the chromosome
    if(n.true.qtl > 1){
      simulated.QTL.POS <- rep.CHROM %>%
      dplyr::filter(Simulated == TRUE) %>%
      dplyr::select(POS) %>%
      as.list()
    
      dist.from.QTL <- list()
      for(j in 1:nrow(rep.CHROM)){
        QTL.dists <- list()
        for(k in 1:length(simulated.QTL.POS[[1]])){
        QTL.dists[[k]] <- rep.CHROM[j,]$POS - simulated.QTL.POS[[1]][k]
      }
      dist.from.QTL[[j]] <- min(abs(unlist(QTL.dists)))
    }
    closest.FP[[i]] <- rep.CHROM %>%
      dplyr::mutate(dist.from.QTL = unlist(dist.from.QTL))%>%
      dplyr::mutate(CHROM = chrom.split$CHROM[[i]])
    
  } else {
    # only 1 simulated QTL on the chromosome
    simulated.QTL.POS  <- rep.CHROM %>%
      dplyr::filter(Simulated == TRUE) %>% 
      dplyr::select(POS) %>%
      as.numeric()
    
    closest.FP[[i]] <- rep.CHROM %>%
      dplyr::mutate(dist.from.QTL = abs(as.numeric(rep.CHROM$POS) - simulated.QTL.POS)) %>%
      dplyr::mutate(CHROM = chrom.split$CHROM[[i]])
  }
} else {
    closest.FP[[i]] <- rep.CHROM %>%
      dplyr::mutate(dist.from.QTL = "Extra-Chromosomal False-Positive")%>%
      dplyr::mutate(CHROM = chrom.split$CHROM[[i]])}
  }
  do.call(rbind, closest.FP) %>%
    as.data.frame() %>%
    dplyr::mutate(Rep = rep, 
                  h2 = h2,
                  algorithm = algorithm)
}
closest.FP.nested <- purrr::pmap(.l = list(reps$data,
                                      reps$Rep,
                                      reps$h2,
                                      reps$algorithm), 
                                 .f = closest.FP.calc)
closest.FP.df <- do.call(rbind, closest.FP.nested)

closest.FP.table <- closest.FP.df %>%
  dplyr::filter(dist.from.QTL != "Extra-Chromosomal False-Positive") %>%
  dplyr::group_by(h2, algorithm) %>%
  dplyr::summarise(mean(as.numeric(dist.from.QTL))) %>%
  tidyr::pivot_wider(names_from = h2, values_from = `mean(as.numeric(dist.from.QTL))`)

closest.ExtraCHROM.FP.table <- closest.FP.df %>%
  dplyr::filter(dist.from.QTL == "Extra-Chromosomal False-Positive") %>%
  dplyr::group_by(h2, algorithm) %>%
  dplyr::summarise(n()) %>%
  tidyr::pivot_wider(names_from = h2, values_from = `n()`)

print(knitr::kable(closest.FP.table, 
                   format = "pandoc",
                   caption = "Average Distance Between False-Positives and the Nearest Simulated QTL",
                   digits = 3))

print(knitr::kable(closest.ExtraCHROM.FP.table, 
                   format = "pandoc",
                   caption = "Number of Extra-Chromosomal False-Positives",
                   digits = 3))

```

```{r interval width plots, echo=FALSE}
summarized %>%
  dplyr::mutate(h2 = as.numeric(levels(h2))[h2]) %>%
  ggplot(., mapping = aes(x = h2, y = mean.interval.Mb, colour = algorithm)) +
  theme_minimal() +
  geom_pointrange(aes(ymin = mean.interval.Mb-sd.interval.Mb,
                      ymax = mean.interval.Mb+sd.interval.Mb), alpha = 0.7) +
  scale_colour_manual(values = nationalparkcolors::park_palettes$Hawaii[c(5,1,2)], name = "Mapping Algorithm") + 
  labs(title = "QTL Resolution v. Heritability",
       x = expression(italic(h^2)),
       y = "Mean QTL Interval Width (Mb)")
```

```{r IntraChromosomal FPsecho=FALSE, fig.height=5.5, fig.width=8, message=FALSE, warning=FALSE, paged.print=TRUE}
closest.FP.df %>%
  dplyr::filter(dist.from.QTL != "Extra-Chromosomal False-Positive") %>%
  dplyr::filter(as.numeric(dist.from.QTL) > 0) %>%
  dplyr::arrange(h2) %>%
  ggplot(., mapping = aes(x = as.numeric(dist.from.QTL)/1000000, stat(count), fill = h2)) + 
  theme_minimal() + 
  geom_density( position = "stack") + 
  facet_grid(algorithm~.) + 
  scale_fill_brewer(palette = "Greens", name = "Trait Heritability") + 
  theme(legend.position = "top") + 
  labs(x = "False-Positive Distance from Nearest Simulated QTL (Mb)",
       y = "Frequency")

closest.FP.df %>%
  dplyr::filter(dist.from.QTL != "Extra-Chromosomal False-Positive") %>%
  dplyr::filter(as.numeric(dist.from.QTL) > 0) %>%
  dplyr::arrange(h2) %>%
  ggplot(., mapping = aes(x = as.numeric(POS)/1000000, y = log10p, fill = h2)) +
  theme_minimal() +
  geom_point(alpha = 0.4, shape = 21) +
  facet_grid(.~CHROM) +
  labs(x = "Genomic position (Mb)",
       y = expression(-log[10](italic(p)))) +
  scale_fill_brewer(palette = "Greens", name = "Trait Heritability") +
  theme(legend.position = "top") + 
  ggtitle("Intra-Chromosomal False-Positives")

closest.FP.df %>%
  dplyr::filter(dist.from.QTL != "Extra-Chromosomal False-Positive") %>%
  dplyr::filter(as.numeric(dist.from.QTL) > 0) %>%
  dplyr::arrange(h2) %>%
  ggplot(., mapping = aes(x = as.numeric(POS)/1000000, y = log10p, fill = algorithm)) +
  theme_minimal() +
  geom_point(alpha = 0.4, shape = 21) +
  facet_grid(.~CHROM) +
  labs(x = "Genomic position (Mb)",
       y = expression(-log[10](italic(p)))) +
  scale_fill_manual(values = nationalparkcolors::park_palettes$Hawaii[c(5,1,2)], name = "Mapping Algorithm") + 
  theme(legend.position = "top") + 
  ggtitle("Intra-Chromosomal False-Positives")

for.binning <- closest.FP.df %>%
  dplyr::filter(dist.from.QTL != "Extra-Chromosomal False-Positive") %>%
  dplyr::filter(as.numeric(dist.from.QTL) > 0) %>%
  dplyr::group_by(CHROM, algorithm) %>%
  tidyr::nest()
fp.bins <- function(data, chrom, algo){
  data %>%
  dplyr::mutate(pos.bin = cut(as.numeric(peakPOS), 10000)) %>%
  dplyr::group_by(pos.bin) %>%
  dplyr::summarise(mean(log10p), median(POS), n()) %>%
  dplyr::mutate(CHROM = chrom,
                algorithm = algo)
}
fp.bins.list <- purrr::pmap(.l = list(for.binning$data, 
                                    for.binning$CHROM,
                                    for.binning$algorithm), .f = fp.bins)
fp.bins.df <- do.call(rbind, fp.bins.list) %>%
  dplyr::mutate(`mean(log10p)` = dplyr::if_else(`mean(log10p)` == "Inf", 
                                                true = 0, 
                                                false = `mean(log10p)`),
                top.end = `n()` > quantile(`n()`, seq(0,1, by = 0.05))[20])
ggplot(fp.bins.df, mapping = aes(x = `median(POS)`/1000000, y = `n()`, fill = top.end)) +
  theme_minimal() +
  geom_point(shape = 21) +
  facet_grid(algorithm~CHROM, scales = "free", space = "free") +
  labs(x = "Genomic position (Mb)",
       y = "Number of False-Positives per Bin") +
  scale_fill_manual(values = nationalparkcolors::park_palettes$Yellowstone[c(3,6)], name = "Top 5%") + 
  theme(legend.position = "top") + 
  ggtitle("Intra-Chromosomal False-Positives")

```

```{r ExtraChromosomal FPs echo=FALSE, fig.height=5.5, fig.width=8, message=FALSE, warning=FALSE, paged.print=TRUE}
closest.FP.df %>%
  dplyr::filter(dist.from.QTL == "Extra-Chromosomal False-Positive") %>%
  dplyr::arrange(h2) %>%
  ggplot(., mapping = aes(x = as.numeric(POS)/1000000, y = log10p, fill = h2)) +
  theme_minimal() +
  geom_point(alpha = 0.4, shape = 21) +
  facet_grid(.~CHROM) +
  labs(x = "Genomic position (Mb)",
       y = expression(-log[10](italic(p)))) +
  scale_fill_brewer(palette = "Greens", name = "Trait Heritability") +
  theme(legend.position = "top") + 
  ggtitle("Extra-Chromosomal False-Positives")

closest.FP.df %>%
  dplyr::filter(dist.from.QTL == "Extra-Chromosomal False-Positive") %>%
  dplyr::arrange(algorithm) %>%
  ggplot(., mapping = aes(x = as.numeric(POS)/1000000, y = log10p, fill = algorithm)) +
  theme_minimal() +
  geom_point(alpha = 0.5, shape = 21) +
  facet_grid(.~CHROM) +
  labs(x = "Genomic position (Mb)",
       y = expression(-log[10](italic(p)))) +
  scale_fill_manual(values = nationalparkcolors::park_palettes$Hawaii[c(5,1,2)], name = "Mapping Algorithm") + 
  theme(legend.position = "top") + 
  ggtitle("Extra-Chromosomal False-Positives")

for.binning <- closest.FP.df %>%
  dplyr::filter(dist.from.QTL == "Extra-Chromosomal False-Positive") %>%
  dplyr::group_by(CHROM, algorithm) %>%
  tidyr::nest()
fp.bins <- function(data, chrom, algo){
  data %>%
  dplyr::mutate(pos.bin = cut(as.numeric(peakPOS), 10000)) %>%
  dplyr::group_by(pos.bin) %>%
  dplyr::summarise(mean(log10p), median(POS), n()) %>%
  dplyr::mutate(CHROM = chrom,
                algorithm = algo)
}
fp.bins.list <- purrr::pmap(.l = list(for.binning$data, 
                                    for.binning$CHROM,
                                    for.binning$algorithm), .f = fp.bins)
fp.bins.df <- do.call(rbind, fp.bins.list) %>%
  dplyr::mutate(`mean(log10p)` = dplyr::if_else(`mean(log10p)` == "Inf", 
                                                true = 0, 
                                                false = `mean(log10p)`),
                top.end = `n()` > quantile(`n()`, seq(0,1, by = 0.05))[20])

ggplot(fp.bins.df, mapping = aes(x = `median(POS)`/1000000, y = `n()`, fill = top.end)) +
  theme_minimal() +
  geom_point(shape = 21) +
  facet_grid(algorithm~CHROM) +
  labs(x = "Genomic position (Mb)",
       y = "Number of False-Positives per Bin") +
  scale_fill_manual(values = nationalparkcolors::park_palettes$RockyMountains[c(1,4)], name = "Top 5%") + 
  theme(legend.position = "top") + 
  ggtitle("Extra-Chromosomal False-Positives")
```

```{r eval=FALSE, include=FALSE}
rep = as.character(sample(seq(1:50), size = 1))
rep = "1"
herit = "0.6"
algo = "LMM-EXACT-INBRED"
closest.FP.df %>%
  dplyr::filter(Rep == rep,
                h2 == herit,
                algorithm == algo) %>%
  dplyr::select(QTL, Rep, dist.from.QTL, Simulated, Detected, Frequency, CHROM, peakPOS)
```

