---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

[CeNDR](https://www.elegansvariation.org/) is a resource maintained by the Andersen Lab which enables the collection and organization of *C. elegans* wild isolates for quantitative genetics and gene discovery. Recently, we have re-vamped our genome-wide association (GWA) mapping pipeline and expanded set of strains and genetic variants available for exploration. Analyses using simulations are currently ongoing to determine the power and utility of *C. elegans* for quantitative genetics.

1. A [small overview](powerprecisionh2.html) of mapping performance with a single QTL with a defined effect.
2. A [more nuanced example](gamma.effects.html) where there are a small collection of QTLs with effects that are distributed more closely to what we expect to see in nature.
3. We dissected false-positive rates in this GWA pipeline, with a specific focus on how they can help us conceptualize [confidence intervals](FPR_CI.html) and divergent regions and [different types of variant sets](variant.set.comp.html) can affect mapping results
4. *C. elegans* strains from around the world have vastly different evolutionary histories, shaping genomic variation in different ways. We interrogated how [population composition](population.comparison.html) affects GWA performance.